### ISSUE TITLE
Proxy-Authorization header for on-premise MAIL destination in java 

### ISSUE THREAD

**Issue by jjtang1985** [SAP/cloud-sdk#1093]
This feature request is copied from [here](https://github.com/SAP/cloud-sdk-js/issues/2983)

> Hi colleagues,
 In the node.js version of the SDK I am able to retrieve the proxy-authorization headers from an on-premise destination of type MAIL, but with the java version as far as I can see the decoration with the additional headers is available only for http destinations (com.sap.cloud.sdk.cloudplatform.connectivity.ScpCfHttpDestination.canDecorate(DestinationProperties)).
 It would be convenient for me if I can retrieve those headers or the jwt token for connectivity either as part of a destination or as a separate API.
 I am using the Cloud SDK within an app on CF.
Thank you,
Milen

I'm creating this ticket on behalf of @mvmanov

**Comment by jjtang1985** [comment]
Hi colleagues, the author provided more details in the original ticket.
It would be great to have a check there.

**Comment by MatKuhr** [comment]
Hi @mvmanov, sorry for the delayed response. Currently we don't have concrete plans to introduce a fully featured mail client into the SDK for Java. So for the moment custom code is needed to send emails.

However, there is another simplification that you could apply to reduce your code complexity. The following code will give you the on-premise proxy headers:
```java
Map<String, String> mapping =
                ScpCfServiceDestinationLoader.buildClientCredentialsMapping(
                        "credentials.url",
                        "credentials.clientid",
                        "credentials.clientsecret",
                        "credentials.token_service_url");
HttpDestination destination =
                ScpCfServiceDestinationLoader.getDestinationForService(
                        "connectivity",
                        "my-connectivity", // give the name of your binding here
                        AuthenticationType.OAUTH2_CLIENT_CREDENTIALS,
                        mapping);
proxyAuthHeader = destination.getHeaders(new URI(""))
                .stream()
                // don’t mind that this is the “Authorization” header, you can use it as proxy-authorization header
                .filter(header -> header.getName().equals(HttpHeaders.AUTHORIZATION)) 
                .findFirst()
                .get()
                .getValue();
```

This internally handles loading the service binding and performing the token flow, which you currently do yourself if I understood correctly. This API may simplify it a bit, especially since it also handles Kubernetes environments.
Right now, this API does not support user token exchange or X509 authentication. If you need that please let us know, we have these improvements on the radar.

I'll close this item for now. Please re-open if you have further questions on the topic 😉

Kind regards,
Matthias
