### ISSUE TITLE
Missing API reference documentation

### ISSUE THREAD

**Issue by sbaltes** [SAP/cloud-sdk#1125]
Hi,

For Java, the API documentation linked on [help.sap.com](https://help.sap.com/docs/SAP_CLOUD_SDK) ("Latest Version of the API Documentation") points to [version 3.55.0](https://help.sap.com/doc/b579bf8578954412aea2b458e8452201/1.0/en-US/index.html) (current version: 4.1.0).

For JavaScript, the link in the [README](https://github.com/SAP/cloud-sdk-js) ("Check our API documentation") points to a [broken link](https://sap.github.io/cloud-sdk/docs/js/api).

On the [GitHub page](https://sap.github.io/cloud-sdk/), I didn't find an overview page listing all available API classes/methods, usually referred to as [reference documentation](https://learn.microsoft.com/en-us/style-guide/developer-content/reference-documentation).

Where can I find this information?

Thanks,
Sebastian

PS: I'm an SAP employee, you can also reach me via E-Mail, Teams, or Slack.

**Comment by jjtang1985** [comment]
Hi @sbaltes , 

Thanks for raising up.
> For JavaScript, the link in the [README](https://github.com/SAP/cloud-sdk-js) ("Check our API documentation") points to a [broken link](https://sap.github.io/cloud-sdk/docs/js/api).

I created a [PR](https://github.com/SAP/cloud-sdk-js/pull/3043) for fixing the js broken link.

> On the [GitHub page](https://sap.github.io/cloud-sdk/), I didn't find an overview page listing all available API classes/methods, usually referred to as [reference documentation](https://learn.microsoft.com/en-us/style-guide/developer-content/reference-documentation).

I feel you are talking about the API doc.
If so, you can find the link either from the PR I created or like the screenshot below:

<img width="1707" alt="Screenshot 2022-11-10 at 18 16 27" src="https://user-images.githubusercontent.com/33489572/201162865-f0a531c6-41c3-4ec7-b106-c79b569a5810.png">

Let me know, if you have questions.

**Comment by jjtang1985** [comment]
@newtork , please check the question related to Java.

**Comment by newtork** [comment]
Hi Sebastian,

That's correct, we stopped uploading newer versions of JavaDoc to `help.sap.com/doc/` due to organizational overhead and questionable effort-result conditions.

We are planning to bring back the JavaDoc HTML, to GitHub Pages. But due to repository size and usability limitations, we will maintain only one JavaDoc release per major version. **This will still be happening in this quarter.**

Until then I can only emphasize: The general API and its behavior has not changed much between `3.56.0` and `4.0.1`. For details you could [checkout our release notes](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java) and maybe also [the migration guide](https://sap.github.io/cloud-sdk/docs/java/guides/4.0-upgrade). Furthermore, we publish the sources including JavaDoc to _Maven Central_ and _Artifactory_. Some IDEs are able to automatically download and display the JavaDoc within your own code usage, e.g. IntelliJ.

Please let me know if you want to be notified as soon as the JavaDoc is available on our documentation portal, i.e. GitHub Pages.

Kind regards
Alexander

**Comment by sbaltes** [comment]
Hi Alexander,

thanks for your detailed reply.

> Please let me know if you want to be notified as soon as the JavaDoc is available on our documentation portal, i.e. GitHub Pages

That'd be great!

Best regards,
Sebastian

**Comment by MatKuhr** [comment]
It took a while, but since end of last year that Javadoc is now also uploaded again and available [here](https://sap.github.io/cloud-sdk/java-api/v5/index.html).
