### ISSUE TITLE
Question about ResponseWithErrorCode (Move from sdk 3 to 4)

### ISSUE THREAD

**Issue by NathanHayoun** [SAP/cloud-sdk#1187]
Hello, 

I am switching to Cloud SDK 4 and I saw that the api: com.sap.cloud.sdk.cloudplatform.servlet.response.ResponseWithErrorCode has been removed. 
Can you tell me if it has been placed elsewhere, or if you have another solution to replace this class ? I could not find this answer in the documentation. 

Thanks a lot,
Best Regards

**Comment by KavithaSiva** [comment]
Hello @NathanHayoun ,

Thanks for reaching out to us.
Yes, **com.sap.cloud.sdk.cloudplatform.servlet.response.ResponseWithErrorCode** along with few other response and exception classes were removed as they were mostly legacy code.
We have hence also adapted the places were these classes were used internally within the SDK so that the current version does not depend on these classes.
Can you please give me code snippets or explain how you are using these classes, to give you more input?

Regards,
Kavitha

**Comment by NathanHayoun** [comment]
Hello @KavithaSiva,
Thanks for your feedback.
After investigating it appears it was a Dead Code.

Best Regards, 
Nathan

**Comment by KavithaSiva** [comment]
Okay, thanks for letting us know. I am closing this issue then.
I will adapt the migration guide to also include the removal of these classes.
