### ISSUE TITLE
Timeline for Java 17 support?

### ISSUE THREAD

**Issue by jaydee101** [SAP/cloud-sdk#1240]
## Issue Description

Is there a timeline for Java 17 support? ATM only 8 and 11 (see FAQ)

### Impact / Priority

Impact: Inconvenience...for example, `javax.*` have to be retrofitted into dependencies (instead of `jakarta.*`)

## Project Details

- SAP Cloud SDK: 3.78.0

---

### Checklist

- [X] Checked out the [faq](https://sap.github.io/cloud-sdk/docs/java/frequently-asked-questions#which-java-versions-are-supported-by-the-sap-cloud-sdk)
- [X] Provided the SAP Cloud SDK version

**Comment by newtork** [comment]
Hello @jaydee101,

SAP Cloud SDK is compatible with Java17. But it currently is not compatible with JakartaEE, you are right!

At the moment we do not have an official timeline for JakartaEE support. However, we are actively working on it with priority. We want to finish it by end of the quarter.
If you are interested in being one of the first testers of this feature please let me know. Otherwise, we'll leave this ticket open until we can share concrete updates.

Kind regards
Alexander

**Comment by newtork** [comment]
> I could help with beta-testing, just let me know how to get a **snapshot** and I will klick it into our pom.

Unfortunately `SNAPSHOT` (or milestone) releases are only shared internally in the company.
In case this doesn't exclude you, please reach out to me via internal channels.

We'll update the ticket in any case 👍

**Comment by CharlesDuboisSAP** [comment]
Hello @jaydee101,

The Cloud SDK is now compatible with Java 17. It is available with the release `4.9.0`.
[Here are some instructions on how to migrate to Java 17 and Spring Boot 3](https://sap.github.io/cloud-sdk/docs/java/frequently-asked-questions#spring-boot-3-and-java-17-support).

Best regards,
Charles Dubois
