### ISSUE TITLE
3.39.0 Missing from Maven

### ISSUE THREAD

**Issue by ConnerKid** [SAP/cloud-sdk#150]
https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java notes that 3.39.0 was released on February 25th but navigating to the linked maven page it is not available.

**Comment by newtork** [comment]
Hi Conner,

I'm sorry to inform you that there is a process delay on company side for releasing `3.39.0`. We are trying to accelerate things internally, but right now I can only suggest to wait for another day or two. We'll update this issue as soon as it's available on Maven Central. Thanks for your interest!

Kind regards
Alexander

**Comment by artemkovalyov** [comment]
@ConnerKid, as Alex mentioned, that's an unfortunate coincidence that our usually ordinary release is hanging on redundant approval and a bit out of schedule. That's why I was unable to share the good news with you so far. I keep on my list to ping you as soon as we see it available on Maven Central. We apologize for this inconvenience.

**Comment by newtork** [comment]
The version is public finally. Please try again :+1:
