### ISSUE TITLE
Support for adding headers in batch mode

### ISSUE THREAD

**Issue by KurtStauffer** [SAP/cloud-sdk#156]
## Issue Description

According to the [Integration guide for Contacts OData](https://help.sap.com/viewer/0f9408e4921e4ba3bb4a7a1f75f837a7/2102.500/en-US/95f2c87395bb4dda905010423029c23e.html) the ```Sap-Cuan-SequenceId``` header is mandatory when updating a ContactOriginData record. When updating in singleton mode I am able to set this header as follows and it works without issue:

```
service
  .updateContactOriginData(contact)
  .withHeader("Sap-Cuan-SequenceId", "PatchUpdate")
  .executeRequest(destination);
```

However, there is no option to set this header when performing the same update in batch mode:

```
service
  .batch()
  .beginChangeSet()
  .updateContactOriginData(contact)
  .withHeader(...) // this option does not exist
  .endChangeSet()
  .executeRequest(destination);
```
When I run the batch request my SAP Import Monitor shows the error:
```
Invalid content in field Sap-Cuan-SequenceId
```
Perhaps I am missing something but this appears to be a shortcoming in the batch mode implementation for the OData v2 typed client to not be able to set the required header. I should note that we are connecting to a SAP S/4HANA Cloud system and so switching to use OData v4 doesn't appear to be an option for us.

Also, before posting here I did ask [this same question](https://stackoverflow.com/questions/66499939/unable-to-set-mandatory-headers-for-contactorigindata-patch-in-batch-mode) over at StackOverflow and was encouraged to log the issue here.

Any help would be greatly appreciated!

Thanks,
Kurt

[mvn_dep_tree.txt](https://github.com/SAP/cloud-sdk/files/6103503/mvn_dep_tree.txt)

### Impact / Priority

Affected development phase: Development

Impact: Blocked

Timeline: Go-Live end of March

## Project Details

- SAP Cloud SDK Version: 3.39.0
- OData Service Definition (EDMX) Version: v2
- Link to GitHub repository: project is private
- Project type, for example:
  - [ ] CAP Project
  - [x] SAP Cloud SDK Maven Archetype
  - [ ] None of the above:
- Platform:
  - [ ] Cloud Foundry
  - [ ] Neo
  - [x] None of the above:

---

### Checklist

- [x] Checked out the [documentation](https://sap.github.io/cloud-sdk/docs/java/sdk-java-troubleshooting-frequent-problems) and [Stack Overflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk)
- [x] Description provided with all relevant information
- [ ] Attached debug logs (N/A)
- [x] Attached dependency tree
- [x] Provided the SAP Cloud SDK version & link to relevant source code

**Comment by artemkovalyov** [comment]
Hi @KurtStauffer,

Thanks for moving the issue here. I added it to the top of our backlog to refine this week and investigate the feasibility of a quick fix. I'll get back to you by Friday with possible fix ideas and timeframe options.

You mentioned you plan to go live end of March, can you elaborate more specifics about the deadlines? The runway is pretty short already, especially assuming our bi-weekly release cycle.

**Comment by KurtStauffer** [comment]
Thanks @artemkovalyov, I really appreciate the help! Our deadline is pretty flexible and if needs be we can continue using our current implementation (which is using RestTemplate to send the batch request) until the SDK is ready. I just found the SDK the other day and saw an opportunity to clean up some ugly code on our end. I love what you've done so far and I'm excited to see where it goes from here!

Thanks!

**Comment by MatKuhr** [comment]
Hi @KurtStauffer , 

You can actually already achieve this today with the SDK using [the low-level API](https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client#odata-v2-batch-read-request):

```java
String servicePath = service.getServicePath();

ODataRequestBatch requestBatch =  new ODataRequestBatch(servicePath, ODataProtocol.V2);
ODataRequestUpdate requestUpdate = service. updateContactOriginData(contact)
		.withHeader("Sap-Cuan-SequenceId", "PatchUpdate")
		.toRequest(); // -> this transitions the request from high to low level API

requestBatch.beginChangeset().addUpdate(requestRead).endChangeset();

HttpClient httpClient = HttpClientAccessor.getHttpClient(destination);
ODataRequestResultMultipartGeneric batchResult = requestBatch.execute(httpClient);

// extract information from batch response, by referring to the individual OData request reference
ODataRequestResultGeneric queryResult = batchResult.getResult(requestUpdate);
MyXyzClass result = queryResult.as(MyXyzClass.class);
```

As @artemkovalyov pointed out we will be working to support this on the high level API as well. However, adapting the above solution might still be a step in the right direction. Because the upcoming API will most likely be similar to the above, but without the need of `toRequest()` and the manual response evaluation. 

We already have such a high-level [API for OData V4](https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client#odata-v2-batch-read-request). I would expect the upcoming V2 variant to be similar.

**Comment by Johannes-Schneider** [comment]
Hi @KurtStauffer,

I just wanted to let you know that we shipped a first version of that feature with [Cloud SDK 3.43.0](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java#3430---april-22-2021).
As Matthias outlined already, we tried to stick as close to our existing OData V4 API as possible, so changes in your code should hopefully be minimal.

Please let us know whether the new API works for you.

Thanks and best regards,
Johannes

**Comment by artemkovalyov** [comment]
Hey @KurtStauffer,

We hope the feature works well for you. We'll be closing this issue for now as we haven't heard from you in a while. If you still have any questions don't hesitate to re-open this issue or create a new one.

Cheers!
