### ISSUE TITLE
Issue with winston dependency breaking builds relying on cloud-sdk/util

### ISSUE THREAD

**Issue by edonadei** [SAP/cloud-sdk#206]
**Describe the bug**
Winston dependencies break multiples jenkins builds since the update 3.3.0/3.3.1 to https://github.com/winstonjs/winston/issues/1814

**Expected behavior**
We should use the cloud-sdk dependency without errors from this dependency
It is actually ```"winston": "^3.2.1"```  but it should be ```"winston": "3.2.1"``` or ```"winston": "~3.2.1"```

**Used Versions:**
 - @sap/cloud-sdk-util@1.17.2 but it happens on other versions aswell

**Comment by marikaner** [comment]
Hey @edonadei, I locked the version to 3.3.0. We will probably release a new version tomorrow or Wednesday. You will have to upgrade to the latest version of the SDK though, which will then be 1.22.0. As you are using a very old version, consider the [migration guide](https://sap.github.io/cloud-sdk/docs/js/guides/migrate-to-open-source-version-of-cloud-sdk-for-javascript-typescript/)

**Comment by HoffmannThomas** [comment]
@marikaner I think 3.3.0 has the same issue. The last one that worked was 3.2.1.

**Comment by HoffmannThomas** [comment]
There is a fixed version available now: https://github.com/winstonjs/winston/issues/1814#issuecomment-647682849

**Comment by marikaner** [comment]
> @marikaner I think 3.3.0 has the same issue. The last one that worked was 3.2.1.

I checked the code, the reference to git was introduced in v3.3.1 and fixed in v3.3.2, so theoretically your builds should work without any action now. If there is still something broken, maybe it is related to something else?

**Comment by HoffmannThomas** [comment]
> > @marikaner I think 3.3.0 has the same issue. The last one that worked was 3.2.1.
> 
> I checked the code, the reference to git was introduced in v3.3.1 and fixed in v3.3.2, so theoretically your builds should work without any action now. If there is still something broken, maybe it is related to something else?

Yeah sorry that was a misfire on my part. It worked with npm install + resolution, but our preinstall resolution script was [ignored during an explicit npm install of the module](https://stackoverflow.com/a/46729184) inside of our pipeline.

So yes, only 3.3.1 was affected and our builds are running fine after the release of 3.3.2 without any action on our side ([since the sdk defined "winston@^3.2.1"](https://github.com/SAP/cloud-sdk/blob/f1289182cddb8417d17177e5d3f7ee0ad57269a4/package.json#L40)).
