### ISSUE TITLE
Can cloud-sdk be used on the client side, e.g. in an Angular application?

### ISSUE THREAD

**Issue by wwosik** [SAP/cloud-sdk#598]
When I add "@sap-cloud-sdk/core" to an Angular project it fails to compile, missing a bunch of libraries, such as "Can't resolve 'tls' " needed for @sap/xsenv/lib.

Other missing modules are e.g. 'fs', 'http', 'https', which leads me to thinking, this library is only for the backend / node.js environment.

Is using this SDK in a frontend app a supported scenario at all?

**Comment by FrankEssenberger** [comment]
Hello Wojtek,

thanks for your request. We want the SDK to be also usable for client application. We will have to make a plan how to make this easy for users either by a separate artifact or good documentation. Have you tried using:

https://www.npmjs.com/package/browserify

to replace the tls,http,fs with the browser working replacements? I am no big expert here and I will add a backlog item for us to try out different thing to see how difficult it is to use the SDK in a browser. 

Best
Frank

**Comment by wwosik** [comment]
@FrankEssenberger thank you for your response. Do you think you can share any timeline - whether the feature can be expected this year or 2021Q1?

**Comment by FrankEssenberger** [comment]
I think a simple test if the browserify approach works with the SDK we will do still this year. If this works only documentation is needed. If we are facing issues one has to see how severe they are.

**Comment by tobakk** [comment]
looking for that feature too

**Comment by nazarkulyk** [comment]
I gived a try to build web client with rollup and rollup-plugin-node-polyfills. But getting an error:
```
xsuaa-service.js:16 Uncaught ReferenceError: exports is not defined
at xsuaa-service.js:16
```

**Comment by FrankEssenberger** [comment]
@nazarkulyk thanks for trying this out. Besides that my initial comment:

> I think a simple test if the browserify approach works with the SDK we will do still this year. If this works only documentation is needed. If we are facing issues one has to see how severe they are.

was not really correct. I talked with me colleagues and we had already an E2E test using a react application making a call to a backend system from the app. We have to investigate why this test is still green and did not warn us that there are problems with the SDK used in the frontend/client side directly. So the SDK should work without any additional steps. I marked this issue as a bug.

**Comment by FrankEssenberger** [comment]
Hello @wwosik,

I just retried our react sample app in the E2E tests and I am able to execute requests with the SDK from the client. Could you perhaps share the sample applications and steps to reproduce the error?

Best
Frank

**Comment by tobakk** [comment]
@FrankEssenberger
- create a new Angular project with the angular-cli (ng new), 
- install sap-cloud-sdk core
- generate an odata v2 client based on a meta data file
- make a simple call to the api with the generated client
 -> check the errors in the browser log

This produced the same errors as @wwosik  in the initial comment

**Comment by FrankEssenberger** [comment]
I have been playing around with Angular and got it working. I also added the project to the E2E tests so that we realize if it stops working. I needed the following work around:

- Include @angular-builders/custom-webpack to the dev dependencies
- In the `angular.json` adjust the build target to use the builder:
```
 "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./node-webpack.config.js"
            }...
```
- In the `angular.json adjust the serve target to use the builder:
```
 "serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
```
- In the custom webpack config used above list the following node modules:
```node: {
    crypto: true,
    stream: true,
    zlib: true,
    path: true,
    os: true,
    http: true,
    https: true
  }
```
- In the package.json exclude the node modules without a browser counterpart:
```
"browser": {
      "fs": false,
      "net": false,
      "tls": false
    }
```

Now the project should build and the run locally. Note that the destination lookup can not work locally since we rely on node to do that. You have to pass the destination explicitly to the call:
```
MyEntity.requestBuilder().getAll().execute({url:"myUrl.com,...})
```
I will create a post in our IO repo, where I will explain how this works with the approuter (it will add the destination info to the call) and how locally.

Note: I am sorry that it did not work out of the box. We clearly aim for proper solution and the changes are just a work around. I think if we update our compilation target to something newer than `es5` we should be able to leverage the `es6` imports properly to avoid the compile issues you were facing.

**Comment by tobakk** [comment]
@FrankEssenberger could you please more context of the custom webpack config? I don't see where I have to put the "    crypto: true,
    stream: true,
    zlib: true,
    path: true,
    os: true,
    http: true,
    https: true
  }
" block

**Comment by FrankEssenberger** [comment]
I am already preparing a small document for our page: https://github.com/SAP/cloud-sdk/pull/650. I wanted to link this here but the merging takes a bit longer because `docusaurous` seems to have some bug in the latest version. To your question your create a `node-webpack.config.js` in your project root. Then you reference it in the `angular.json` as mentioned above. The content of the `node-webpack.config.js` should be:

```
module.exports={
  node: {
    crypto: true,
    stream: true,
    zlib: true,
    path: true,
    os: true,
    http: true,
    https: true
  }
}
``` 
This extends the default webpack config with values for the node modules to be compiled in..

**Comment by tobakk** [comment]
perfect! Thank you it worked!

**Comment by FrankEssenberger** [comment]
As I mentioned this work around should not be needed. We are working to get rid of it.

**Comment by FrankEssenberger** [comment]
@tobakk in the document we also put the limitation, because some parts of the SDK like the destination lookup rely on node. But request building, execution and parsing should work in the browser.

**Comment by artemkovalyov** [comment]
@tobakk and everyone who'll follow, the most up to date version of Cloud SDK in Browser can always be found here:
https://sap.github.io/cloud-sdk/docs/js/guides/sdk-in-browser

Thanks, @FrankEssenberger for making this happen :)
