### ISSUE TITLE
Issues Creating Client for SAP B1 EDMX

### ISSUE THREAD

**Issue by ConnerKid** [SAP/cloud-sdk#61]
## Issue Description

When using the SAP B1 EDMX file for OData V4, the generator throws a large amount of errors. This leads to a large amount of functions being unable to be used. Most importantly, anything related to inserting or reading existing documents is not possible with the code generated by the client generator without modifications.

Per the Service Layer documentation, getting an existing document (in this case an 'Order'):

![image](https://user-images.githubusercontent.com/4248385/102127532-9f713380-3e1a-11eb-8a4c-2578f8f6ead9.png)

These types of operations are not possible with the client generator.

Also, on a side note; why does the error reference OData v2 when I am using the V4 client generator?

And is it possible to change the default service path? `String DEFAULT_SERVICE_PATH = "/b1s/V2/SAPB1"` is created but it should be `/b1s/V2/` given the command line arguments.

### Impact / Priority

Blocked from using a large portion of the Service Layer, cannot continue development using service layer.

## Error Message

```
[main] ERROR com.sap.cloud.sdk.datamodel.odatav4.generator.DataModelGeneratorCli - Function import CreditNotesService_RequestApproveCancellation has non-simple type for parameter Document, but OData V2 does not support non-simple types as function import parameters.
```

## Project Details

A simple project to get an existing Order Document given the DocEntry number.

Using version 3.34.1 with command line arguments: `java -jar odata-v4-generator-cli-3.34.1.jar -b "/b1s/V2/"`
---

### Checklist

- [x] Checked out the [documentation](https://sap.github.io/cloud-sdk/docs/java/sdk-java-troubleshooting-frequent-problems) and [Stack Overflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk)
- [x] Description provided with all relevant information

**Comment by artemkovalyov** [comment]
Hi @ConnerKid,

Thanks for reporting this and the specific details. OData is a huge protocol with many features and edge cases and some of them we yet to cover fully.  Are you referring to this service [specification](https://api.sap.com/package/B1Sales?section=Artifacts)? If not, can you provide an EDMX file to this email: cloudsdk@sap.com?

We'll reproduce and issue and update you on possible workarounds or when we can provide a fix for this.

Is this production service development or a PoC?

Best,
Artem

**Comment by ConnerKid** [comment]
Hey @artemkovalyov 

Thank you for your response! I have sent the file to the email you have provided.

This is a productive environment that we are switching from the legacy DI Server to the Service Layer for SAP B1.

**Comment by MatKuhr** [comment]
Hi @ConnerKid,

I took an initial look and I think I can answer some questions.

## Why are the Operations on e.g. "/orders" missing?

The reason is unfortunately a deeply rooted shortcoming of the generator.
The generator expects a 1-1 mapping between `entity types` and `entity sets`.
This is a problem because in the service definition there are in total 24 entity sets for the type `SAPB1.Document".

The SDK simply generates operations for the first entity set of a given type, any following entity sets with the same type are ignored.

We are aware of this shortcoming but so far haven't seen any OData services that actually do expose more than one endpoint per entity type.

-------

Now why is this not straight forward to fix? Because our naming scheme for the generated methods is derived from the entity type and not the entity set. E.g. we will have `getAllDocuments()` instead of `getAllOrders()`. 

If we were to simply change the generator to apply the second approach we would break the code of all customers using generated code.
So we can't do that.
Instead, we'll have to check if we can implement this in a non-breaking, backwards compatible way.

## Why do we see an OData V2 Error Message when Processing Functions?

This is simply a leftover.
For OData V4 we started out with the V2 generator and adapted it to work for OData V4.
As of today the generator doesn't support bound functions and actions just yet.
That is why we never touched that part of the code yet, the error message should actually be a warning:

```txt
"Bound operations are not yet support with the OData generator"
```

----

We are working on supporting bound operations.
We already have a low-level implementation in place that is capable of performing bound functions and actions.


It can be used as follows:
```java
// this code will build the following URL:
// "/service/Entity(key1='foo%2Fbar',key2=123)/Model.Function(param1='foo%2Fbar',param2=123)"

ODataEntityKey key = new ODataEntityKey(ODataProtocol.V4)
    .addKeyProperty("key1", "foo/bar")
    .addKeyProperty("key2", 123);

ODataFunctionParameters  params = new ODataFunctionParameters(ODataProtocol.V4)
    .addKeyProperty("param1", "foo/bar")
    .addKeyProperty("param2", 123);

ODataResourcePath functionPath =
    new ODataResourcePath()
        .addSegment("Entity", key)
        .addSegment("Model.Function", params);

ODataRequestFunction request =
    new ODataRequestFunction("/service", functionPath, null, ODataProtocol.V4);
```

This is basically what usually happens under the hood if you are using the generated code.
But until that is available and you really need to perform these bound operations you can use the above approach.

## Why is the service path incorrect?

The service path is actually generated as intended, although it's somewhat unintuitive when using a single service definition.
Check out the explanation in the yellow box [on the documentation](https://sap.github.io/cloud-sdk/docs/java/features/odata/generate-typed-odata-v2-and-v4-client-for-java#using-the-odata-generator-maven-plugin).

The reason for the behaviour is that oftentimes multiple service definitions will be inputted to the generator at once.
That is why the full path will be assembled from some common value (the `basePath`) and a value from the individual service definition (the `namespace` tag).

## Summary

I hope I could shed some light on the individual problems and we are working to better supporting your requirements in the future.
If possible please share with us your timelines on which functionality you would require by what time.
Also I infer from your description that you made some manual changes to the metadata files to get the generator to complete generation. 
Assuming this is the case: could you also share this version with us?

Also I should say that the service metadata is very large. Usually we see metadata files between 2k and 10k lines. I don't know if you have any reign over the service, but it would be easier if the definitions were smaller.

**Comment by ConnerKid** [comment]
@MatKuhr Thank you for the very detailed response!

To answer your questions:

1. Usually we see metadata files between 2k and 10k lines. I don't know if you have any reign over the service, but it would be easier if the definitions were smaller.

- This metadata is actually from the SAP Business One Service Layer (specifically for version 10 patch level 3). There are quite a few operations and entities involved. I pulled the metadata as described on page 18 of the following PDF with no modifications. [Working_with_SAP_Business_One_Service_Layer.pdf](https://github.com/SAP/cloud-sdk/files/5696443/Working_with_SAP_Business_One_Service_Layer.pdf)

2. Also I infer from your description that you made some manual changes to the metadata files to get the generator to complete generation.

- The modification I made was to the generated `Document` class, specifically the getEntityCollection() method. Unfortunately that doesn't resolve the problem.

3. If possible please share with us your timelines on which functionality you would require by what time.

- The functionality described in `Why are the Operations on e.g. "/orders" missing?`. The way that SAP Business One handles any kind of "Marketing Document" (i.e. Orders, Invoices, Deliveries, etc) is that they are all `SAPB1.Documents` The specific enpoints determine which object is actually being interacted with (/orders or /invoices, for example.) This is the highest priority issue for me, as it prevent us from using the client generator for metadata for SAP B1 Service Layer.

On a side note, is [this issue](https://github.com/SAP/cloud-sdk-js/issues/707) related?

**Comment by MatKuhr** [comment]
You are welcome!

> On a side note, is this issue related?

It's essentially the same feature gap on the JavaScript version of the SDK.

-----

On the main problem of **missing entity sets** basically two workarounds come to my mind:

1. Only generating a subset of the service
1. Not using the generated code but instead hand-writing the requests you need on the low-level API.

Option 1. could mean you replicate the service definitions and make sure each only contains one entity collection. You can remove all definitions you don't need. Of course, this is manual effort and tedious, but should overcome the limitation. If you only need 2 or 3 entity collections this might be a viable workaround.

Option 2. is equally tedious but again should work if you only need few operations. And even support operations that are not yet covered by the generator at all (e.g. bound functions & actions). Because the low-level API was created to be only internally used by the generated code it isn't well documented. And it requires hard-coding some of the information like e.g. function names or of which type a field is. As you can see in the example I gave above. But it gives you the highest flexibility to achieve your requirements.

Both options come with the downside of manual effort scaling up with how much of the service you intend to use. So they can only be short term solutions. In the long term the SDK needs to fill the feature gaps it has today.

**Comment by ConnerKid** [comment]
@MatKuhr Ok, understood! Appreciate all the input.

As far as the workarounds, it is dependent on the timeline I am working with. I understand these are deep-rooted feature gaps that are going to be time consuming to resolve. With that in mind, I will probably pause migrating from the SAP DI Server to the Service Layer since I don't want to duplicate efforts. 

What are the next steps as far as having this as a formal feature request, or is this not something that is planned right now?

**Comment by artemkovalyov** [comment]
@ConnerKid, we already have this added to our backlog and plan to release this functionality as soon as we can. The timing to uncover this gap is a bit unfortunate because of the looming Christmas time so we hardly can provide a comprehensive update before the end of the year.

- You can count this as an official feature request and we have this on our support board.
- This is high in our priorities, but I can't give you a timeline as of now. Please, share your preferred timeline and we'll see what we can do.
- We'll keep this issue open and keep you posted about the progress
- You can follow our release notes for the [latest news](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java) as we might be releasing partial fixes from time to time.

I hope this helps and looking forward to having this resolved soon.

**Comment by ConnerKid** [comment]
@artemkovalyov Hope everyone on your end had a good holiday season!

I was just combing through the release notes of 3.36.0 which was released today and didn't see any mention of this and also no mention in the [matrix](https://sap.github.io/cloud-sdk/docs/overview/cloud-sdk-feature-matrix). Do you know if this is still in the backlog?

**Comment by artemkovalyov** [comment]
Hi @ConnerKid,

Thanks for the question and for bringing our attention back to this. We haven't worked on this yet and I provisionally planned to have it delivered by the end of February. We still have to groom/refine it for a better estimate and making sure we can fit it into one of the sprints.

Does the end of Feb works for you or you have smth going to production which would require it earlier?

**Comment by ConnerKid** [comment]
@artemkovalyov We're planning on modifying some project release timelines based on this being resolved. As long as we have a rough timeline to work with then I'd appreciate it. So the end of February is realistic then?

**Comment by artemkovalyov** [comment]
@ConnerKid, it should be realistic. Let me update you at the end of January as we're going to refine it to figure out possible edge cases. I'll get back to you end of next week.

**Comment by artemkovalyov** [comment]
@ConnerKid, we started an investigation this week. We'll update you on the results as the delivery timeframe will get more clarity.

**Comment by ConnerKid** [comment]
@artemkovalyov Hey! Just wanted to know how the investigation went?

**Comment by MatKuhr** [comment]
Hi @ConnerKid, @artemkovalyov is currently on vacation which is why I am jumping in. 

We started with the implementation and have some good first results. The solution still has to pass some of our QA checks and then should get shipped with the next release which we perform every 2 weeks. 

_If all goes right I would expect_ the functionality to be included with `3.39.0` or `3.40.0` which are scheduled to be available at the start of CW9 and CW11 respectively.

**Comment by artemkovalyov** [comment]
Hi @ConnerKid,

The requested feature was released with 3.39.0. Please, let us know if it worked for you as expected and we can close this issue.

**Comment by ConnerKid** [comment]
@artemkovalyov Yes I can confirm it works and is generating the correct client code!

**Comment by MatKuhr** [comment]
Hi @SpaceCondor, I just wanted to let you know that as of [version 3.46.0](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java#new-functionality) the SAP Cloud SDK for Java has built in support for [bound functions and actions](https://sap.github.io/cloud-sdk/docs/java/features/odata/use-typed-odata-v4-client-in-sap-cloud-sdk-for-java#odata-functions-and-actions).

This allows for building requests directly from the VDM. The entity classes will expose all functions and actions bound to them on the API.

In case you want to use the bound operations in the B1 service this should now be possible from the generated code. In case you have any feedback don't hesitate to share it with us!

**Comment by newtork** [comment]
Hi @SpaceCondor,

In case you face the following message still, feel free to update SAP Cloud SDK to `3.50.0` this week (for internal Nexus) or by end of next week (for Maven Central):
> `[main] ERROR com.sap.cloud.sdk.datamodel.odatav4.generator.DataModelGeneratorCli - Function import CreditNotesService_RequestApproveCancellation has non-simple type for parameter Document, but OData V2 does not support non-simple types as function import parameters.`

We now support non-primitive field types for action parameters:
- Complex types
- Entity types
- Enum types
- Collection types

Please let us know, if you have any comment/opinion.

Kind regards
Alexander

**Comment by SpaceCondor** [comment]
That's great, thank you so much!
