### ISSUE TITLE
Filter encoding

### ISSUE THREAD

**Issue by wm-bilot** [SAP/cloud-sdk#741]
Important information:

Assume there's a field `version` with possible values:
Online|1
Online|2
etc

I want to filter by this field. So I'm trying to create filter like this: 

`Version.KEY.eq("Online|" + supportedVersion)`

this gives me encoding error. So I tried this (`|` encoded to `%7C`):

`Version.KEY.eq("Online%7C" + supportedVersion)`

but it picked `%` and encoded it to `%25`, so it's not a value that I wanted.

Expected outcome would be to either encode all chars including `|` in my case. Or allow to pass already encoded string as a filter and don't encode it second time.

This is blocking issue for my project - can't perform GET with filter operation and skipping filter is not possible due to size of the data. Should go live in a month.

- SAP Cloud SDK Version: 3.66.0

I hope this is simple enough to reproduce that I don't have to include any more information. But let me know if anything is needed.

**Comment by Johannes-Schneider** [comment]
Hi @wm-bilot,

thanks for the clarification.

We are working on a fix, which we hope to ship as soon as possible.
We will keep you posted about any updates on this issue.

Best regards,
Johannes

**Comment by wm-bilot** [comment]
@Johannes-Schneider is there any ETA or release cadence that I could potentially base on?

**Comment by Johannes-Schneider** [comment]
Hi @wm-bilot,

we are currently preparing the release of version `3.67.0`, which also contains the fix for this issue.
Unfortunately, our release has been delayed due to the "Spring4Shell" vulnerability that we need to take care of.

Nevertheless, we are **hoping** to be able to ship the new Cloud SDK version by next Wednesday (13.04.2022) - sorry for the long delay!

**Comment by wm-bilot** [comment]
@Johannes-Schneider any update on this?

**Comment by Johannes-Schneider** [comment]
Hey @wm-bilot,

it took us a little longer than expected to finally release the "Spring4Shell" fix (since we also had to wait for other internal projects to release first).
Nevertheless, you can finally consume Cloud SDK version `3.67.0`, which also fixes the wrong encoding for `|`.

Please let me know whether everything works as expected.

Best regards,
Johannes

**Comment by KavithaSiva** [comment]
I am closing this issue as version `3.67.0` of SAP Cloud SDK is already available in Maven central. Please reopen the issue if you are still facing issues.
