### ISSUE TITLE
Unable to fetch the subscriber tenant destination details using DestinationAccessor service

### ISSUE THREAD

**Issue by AishaFarheenPK123** [SAP/cloud-sdk#774]
We have a microservice implementation with SPQR graphql libraries for API development. 
[https://github.com/leangen/graphql-spqr](url)

When the destinations are accessed from the service using _DestinationAccessor.getDestination()_, it returns the provider tenant destination details rather than the subscriber tenant. 

If we annotate @ServletComponentScan with the application, we are able to fetch the destination from subscriber tenant, but all the graphql queries and mutations are failing with below error

Caused by: java.lang.IllegalStateException: Async support must be enabled on a servlet and for all filters involved in async request processing. This is done in Java code using the Servlet API or by adding "<async-supported>true</async-supported>" to servlet and filter declarations in web.xml.

Please suggest if there is any other approach to fetch the subscriber tenant destination details via cloud sdk service.

**Comment by newtork** [comment]
Hi [AishaFarheenPK123](https://github.com/AishaFarheenPK123),

Please note, we designed the servlet class for simple applications to enable the _SAP Cloud SDK_ for incoming requests. Since we are working on a new major release right now, the future of this class is not yet decided. Changing it now may produce unexpected issues with other consumers.

For use cases like yours, that depend heavily on asynchronous execution, we recommend the `ThreadContextExecutor` API to be used just after spawning a new Thread / entering an asynchronous control flow. There are multiple convenience methods for leveraging this internal API.

This is is a neat convenience API that I would suggest:
```diff
  Map<String, String> requestHeaders; // please look up how to resolve them at (asynchronous) runtime

  public T myAsynchronousMethod() {
+   return RequestHeaderAccessor.executeWithHeaderContainer(requestHeaders, () -> {
      return myDestinationDependentMethod();
+   });
  }

  T myDestinationDependentMethod() {
    // DestinationAccessor.getDestination()
  }
```

I think with that you wouldn't need the `@ServletComponentScan` any longer - just saying :)

Kind regards
Alexander

**Comment by AishaFarheenPK123** [comment]
Hi Alexander,

We have tried the approach you have suggested . Still without @ServletComponentScan annotation, it is pointing to provider tenant destination. Please find the code snippet as below.
Could you please suggest on this.

` RequestHeaderContainer requestHeaders = RequestHeaderAccessor.tryGetHeaderContainer().getOrElse(RequestHeaderContainer.EMPTY);
        ThreadContextExecutor executor = new ThreadContextExecutor().withThreadContext(new DefaultThreadContext()).withListeners(new RequestHeaderThreadContextListener(requestHeaders));
        Callable callS4AndUpdateDB = () -> executor.execute(() -> {

            return DestinationAccessor.getDestination("QM7_910_loki");
        });
        Destination d = (Destination) callS4AndUpdateDB.call();`

Thank You,
Aisha.

**Comment by KavithaSiva** [comment]
Hi @AishaFarheenPK123,

In your approach, you used the `RequestHeaderAccessor` to resolve the request headers.
This won't because the accessor internally tries to read the headers from a `ThreadContext`(a Cloud SDK internal storage object) which only gets created when you instantiate a `ThreadContextExecutor` in the subsequent line, so I assume your `requestHeaders` are empty instead.

Can you tell me in more about your asynchronous use case, we have to figure out how to obtain access to the request headers during asynchronous runtime.

Regards,
Kavitha

**Comment by KavithaSiva** [comment]
Discussion continued in [internal GH.](https://github.wdf.sap.corp/MA/sdk/issues/6905)

**Comment by KavithaSiva** [comment]
Closing this issue as the customer obtained access to the request headers by using `@GraphQLRootContext DefaultGlobalContext<ServletWebRequest> context`
