### ISSUE TITLE
Unable to retrieve destinations with Authentication OAuth2JWTBearer

### ISSUE THREAD

**Issue by jain24akash** [SAP/cloud-sdk#859]
## Issue Description

Important information:

- Your code
        String DESTINATION_NAME = "testm";
        ScpCfDestinationLoader destinationLoader = new ScpCfDestinationLoader();
        DestinationAccessor.setLoader(destinationLoader);
        Try<Destination> destinations = destinationLoader.tryGetDestination(DESTINATION_NAME);
        System.out.println(destinations.toString());

- Expected outcome
        Expected outcome is to be able to retrieve the destination successfully
- Actual outcome
       Getting Failure, Failed to get Destination.
- Steps attempted to resolve the issue
- In case of issues with any of our VDMs:
  - What happens when a request is performed directly via an HTTP client tool such as Postman?
  - In case that succeeds please provide details on the request such as URL, query parameters, header parameters, prerequisite requests (e.g. CSRF token), etc.
- Potentially missing information (open questions you might have)

### Impact / Priority

Affected development phase: Getting Started, Development

Impact: Blocked

## Error Message

```
Please paste your stack trace here within the backticks (replacing this comment)
```

## Project Details

- SAP Cloud SDK Version: 3.68.0

- Link to GitHub repository: https://github.wdf.sap.corp/c4u/c4u-mkv-mesoto
- Project type, for example:
  - [X] CAP Project
  - [ ] SAP Cloud SDK Maven Archetype
  - [ ] None of the above:
- Platform:
  - [X] Cloud Foundry
  - [ ] Neo
  - [ ] None of the above:

---

### Checklist

- [X] Checked out the [documentation](https://sap.github.io/cloud-sdk/docs/java/sdk-java-troubleshooting-frequent-problems) and [Stack Overflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk)
- [X] Description provided with all relevant information
- [ ] Attached debug logs
- [ ] Attached dependency tree
- [X] Provided the SAP Cloud SDK version & link to relevant source code

**Comment by KavithaSiva** [comment]
Hi @jain24akash,

Thanks for reaching out to us. Can you please give us more details on the error you encounter while trying to fetch the destination. 
Please attach the stack trace, DEBUG logs so that we can analyse this further. (As this public GH, you can also shift to our organisation's GH [issues](https://github.wdf.sap.corp/MA/sdk/issues) to share the logs).
You can refer to this [document](https://sap.github.io/cloud-sdk/docs/java/guides/logging-overview#recommendation-for-spring-boot-eg-sap-cloud-application-programming-model) to enable debug logging.

Regards,
Kavitha
