### ISSUE TITLE
Reflection for RFC and BAPI to create pojos

### ISSUE THREAD

**Issue by gman77** [SAP/cloud-sdk#931]
Hi,

I really like using this abstraction to get the RFC and BAPI.
Also, the error handling of missing fields and incorrect datatypes.

It would be great if there was a way to generate the pojos through reflection of the 
rfcs/bapis instead of doing them manually.

**Comment by newtork** [comment]
Hi @gman77,

Thank you for the question! We're always interested in understanding customer use-cases. Are you addressing a custom RFC/BAPI directly? Or is it maybe a _SOAP_ service listed in the [SAP API Business Hub](https://api.sap.com/)? For the latter option we're currently evaluating future support.

If you can derive a _WSDL_ file from your RFC/BAPI case, then we would recommend using [AXIS2](https://axis.apache.org/axis2/java/core/index.html) to generate service and POJO classes. That's what we did some years ago, before we paused further development. However it should be compatible with the `HttpClient` from our `HttpClientAccessor` API. If you face any blockers, please let us know.

In case the connectivity is based on _JCo_ instead of _SOAP_, then I'm afraid I don't have a specific recommendation. I would approach the _JCo_ colleagues directly then.

Kind regards
Alexander

**Comment by gman77** [comment]
Thanks will give it a try.
